---
provision:
    ip_address: "192.168.0.126"
    netmask: "255.255.255.128"
    forward:
        type: "nat"
internal:
storage:
external:
management:
    forward:
        type: "nat"
    ip_address: "172.16.17.254"
    netmask: "255.255.255.128"
    dhcp:
        range:
            start: "172.16.17.130"
            end: "172.16.17.150"
        subnet_cidr: "172.16.17.128/25"
        subnet_gateway: "172.16.17.254"
    ipv6_address: "2001:db8:ca2:3::1"
    ipv6_prefix: 64
