- name: check for existing networks
  virt_net:
      command: "list_nets"
  register: network_list

- name: create the networks for the topology
  virt_net:
      command: "define"
      name: "{{ item.key }}"
      xml: "{{ lookup('template', '../templates/network.xml.j2') }}"
  when: "item.key not in network_list.list_nets"
  with_dict: "{{ provisioner.topology.network }}"

- name: check if network is active
  virt_net:
      state: active
      name: "{{ item }}"
  with_items: "{{ provisioner.topology.network.keys() }}"

- name: make network persistent
  virt_net:
      name: "{{ item }}"
      autostart: "yes"
  with_items: "{{ provisioner.topology.network.keys() }}"

- name: create ifcfg script for tagged external network
  copy: src=ifcfg-external.100 dest=/etc/sysconfig/network-scripts/ifcfg-external.100
  notify: apply masquerading rules for external tagged network
