- name: check for existing networks
  virt_net:
      command: "list_nets"
  register: network_list

- name: create the networks for the topology
  virt_net:
      command: "define"
      name: "{{ item.key }}"
      xml: "{{ lookup('template', '../templates/network.xml.j2') }}"
  when: "item.key not in network_list.list_nets"
  with_dict: "{{ provisioner.topology.network }}"

- name: check if network is active
  virt_net:
      state: active
      name: "{{ item }}"
  with_items: "{{ provisioner.topology.network.keys() }}"

- name: make network persistent
  virt_net:
      name: "{{ item }}"
      autostart: "yes"
  with_items: "{{ provisioner.topology.network.keys() }}"

- name: create manual networking setting
  copy: src="{{ item }}" dest="/etc/sysconfig/network-scripts/{{ item }}"
  with_items:
    - ifcfg-external.100
    - ifcfg-external.101
    - ifcfg-internal.201
  notify: set up manual networking
