---
- name: Set selinux state
  tags: backup
  hosts: openstack_nodes
  become: yes
  become_method: sudo
  tasks:
    - selinux: policy=targeted state={{ installer.selinux|default('enforcing') }}

- include: "installer/{{ installer.type }}/main.yml"

- name: Update the inventory file
  hosts: localhost
  gather_facts: no
  tasks:
      - name: Generate new Inventory file
        template:
          dest: "{{ lookup('env', 'PWD') }}/hosts-{{ lookup('env', 'USER') }}"
          src: "{{ inventory_dir }}/templates/inventory.j2"

      - name: Link to new Inventory file
        file:
          dest: "{{ lookup('env', 'PWD') }}/hosts"
          state: link
          src: "{{ lookup('env', 'PWD') }}/hosts-{{ lookup('env', 'USER') }}"
